### ISSUE TITLE
Undelcared Identifier: SolidPaint

### ISSUE THREAD

**Issue by general-rishkin** [Vindaar/ggplotnim#168]
I just installed ggplotnim.
On use, it produces the error: 
```.nimble/pkgs2/ginger-0.3.13-4f7c989ddb9489d39d7c81bf5a6966d603cf3a60/ginger/backendPixie.nim(27, 29) Error: undeclared identifier: 'SolidPaint' candidates (edit distance, scope distance)```

**Comment by Vindaar** [comment]
For all intents and purposes the Pixie backend is not really supported at the moment. It needs some fixups (and as you can see) changes due to upstream Pixie changes. 

It's a low priority issue for the time being. I have my hands too full at the moment. Feel free to attempt to fix it. Otherwise I'll get to it eventually, but I'm not making any statements about when that might be. Those have been too wrong too many times lately...

Just use it with the Cairo backend unless that is for some reason not an option.

(In any case this is technically a ginger issue, but as ginger doesn't really have users it's fine here).

**Comment by general-rishkin** [comment]
OK, thanks, will do.
