### ISSUE TITLE
stat="identity" for aes

### ISSUE THREAD

**Issue by danielecook** [Vindaar/ggplotnim#19]
Hi this is great! is it possible to specify that the aes use the identity rather than computing groups or transforming numbers?

I am trying to plot a histogram where I have already computed the frequencies.

**Comment by Vindaar** [comment]
Thanks!

Unfortunately that's not possible yet. So far all stats are hardcoded depending on type and discreteness. 

In order to add support I mainly have to refactor the whole histogram / freqpoly proc, which is *long* overdue. I mean just look at this horrible mess: https://github.com/Vindaar/ggplotnim/blob/master/src/ggplotnim.nim#L1162-L1304

I'll make it a priority!

**Comment by Vindaar** [comment]
Just hacked something together to see if the idea I had in my mind is in principle correct. I pushed it here https://github.com/Vindaar/ggplotnim/tree/addStatIdentity.

I introduced some questionable changes and haven't actually done the refactoring I mentioned. Also it only works for histograms (probably only for those without any additional scales, e.g. color). I tested it with this:

```nim
import ggplotnim, sequtils, seqmath

let x = @[0, 1, 2, 3]
let y = @[0.1, 0.4, 0.3, 0.2]
let df = seqsToDf(x, y)

ggplot(df, aes("x", "y")) +
  geom_histogram(stat = "identity") + 
  ggsave("test.pdf")
```

**Comment by danielecook** [comment]
@Vindaar thanks this is a big help. I'm using this to output a plot from a CLI...very nice not to have to call an external library.

**Comment by Vindaar** [comment]
Ok this took way longer than I thought it would, since I had to change a lot more code than initially planned (or rather I thought it was a good time to do that).

The PR #18 still is not quite finished in terms of the tests, but on my end all functionality is there and `stat="identity"` is working flawlessly. `bin` and `count` on the other hand should now also work on other geoms, but I haven't tried it yet.

**Comment by danielecook** [comment]
Wow @Vindaar - This is a great addition. Thanks so much! This will be very useful for generating plots as part of command line utilities.

**Comment by Vindaar** [comment]
I finally managed to get everything working as intended and merged the PR. 

Check out the recipes https://github.com/Vindaar/ggplotnim/blob/master/recipes.org for an example of plotting already binned data. Let me know if something doesn't work as you expect it to!
