### ISSUE TITLE
How to handle -inf float values when plotting?

### ISSUE THREAD

**Issue by kaushalmodi** [Vindaar/ggplotnim#44]
Hello,

I was debugging why my FFT plotting was crashing randomly.. 

```
/home/kmodi/.nimble/pkgs/ggplotnim-0.2.8/ggplotnim.nim(2780) +
/home/kmodi/.nimble/pkgs/ggplotnim-0.2.8/ggplotnim.nim(2770) ggsave
/home/kmodi/.nimble/pkgs/ggplotnim-0.2.8/ggplotnim.nim(2707) ggcreate
/home/kmodi/.nimble/pkgs/ggplotnim-0.2.8/ggplotnim.nim(2083) generatePlot
/home/kmodi/.nimble/pkgs/ggplotnim-0.2.8/ggplotnim.nim(1946) handleTicks
/home/kmodi/.nimble/pkgs/ggplotnim-0.2.8/ggplotnim.nim(1847) handleContinuousTicks
/home/kmodi/.nimble/pkgs/ginger-0.1.7/ginger.nim(2069) initTicks
/home/kmodi/.nimble/pkgs/ginger-0.1.7/ginger.nim(2035) initTicks
Error: unhandled exception: Either need a number of ticks or tick locations if auto tick locations not used! [ValueError]
```

After narrowing down to a small data set, I found, **-inf** (valid Nim float value) as part of the data that I was plotting:

```nim
@[-191.5243109538998, -209.7186267027922, -232.2594043180185, -260.5427208848885, 
-297.3832809546469, -340.377384815329, -340.377384815329, -inf, -inf, -334.3567849020494, 
-333.3876847719688, -335.3258850321299, -346.3979847286086, -351.9555844453586, 
-353.3834456844492, -343.9815618770165, -350.4117593147899, -340.4695264529317, 
-354.4025139469563, -340.1113149084508]
```

The error kind of makes sense.. but what's the best way of handling `-inf` in random data sets?

Thanks.

*PS: I still need to try out the annotation feature, but was caught up in this debug.*

**Comment by Vindaar** [comment]
Hmm, so the data you show in your post is one of the columns you're trying to plot?

Yes, it's certainly possible that `inf` values currently do bad things. 

The error you see is, if I'm not mistaken from the top of my head, coming from the fact that the calculation for the ticks looks at the data on the corresponding scale. Then it encounters an `inf` and fails, because it doesn't know how to deal with that. :)

Right now I'm mostly wondering what should be done with values containing `inf`? Should they just be dropped? For the calculation of the associated data scales and ticks that seems to make sense. Well, if one scale has an `inf` value it can't be represented on the plot anyways. Remains the question of where to drop them in the code (for instance we probably don't want to filter the input DF for `inf`, because that would just be a waste for most inputs), but that's my problem. On the other hand should the user be notified that values are dropped?

Can you give me a more complete example? Maybe just the content of the data frame and the calls you do? Then I know what the plot is probably supposed to look like. Although I guess it's just an FFT similar to the one from the previous issue.


Regarding the annotations:
Make sure to update your `ginger` to version `v0.1.8`!

**Comment by kaushalmodi** [comment]
> Hmm, so the data you show in your post is one of the columns you're trying to plot?

Oops, yes. That's the y seq. The x seq can be `0 ..< y.len`.

> Right now I'm mostly wondering what should be done with values containing inf?

Assuming that the `-inf` (or `inf`) is not there, let's say that the min value is `yMin`. Then you decide some buffer of blank space below it so that `yMin` does not touch the bottom border of the plot.

Now if the `-inf` is there, can you make that `-inf` point touch the bottom of the plot i.e. at `-yMin - buffer`? I am basically thinking of how the `tan` plots are done:

![](https://i.stack.imgur.com/OzIrr.png)

I hope that makes sense. 

> Should they just be dropped? 

I wouldn't drop them, as it was falsify the plot. For e.g., in an FFT plot, `-inf` for a freq means that that freq of sine tone is absolutely not present in the analyzed data of multiple sine tones.

> Although I guess it's just an FFT similar to the one from the previous issue.

Yes :)

> Can you give me a more complete example? Maybe just the content of the data frame and the calls you do? 

I don't have a complete example, because the FFT is done by MATLAB.. I gather data in a SystemVerilog simulation, send it to MATLAB to calculate FFT that returns me an array of power spectral densities (that short snippet above was from a 130k sample set of PSD's).. That PSD is passed as y seq to ggplotnim.

While I don't have a good way to reproduce the entire example, I will provide a quick example to reproduce that crash.

**Comment by kaushalmodi** [comment]
Here's an example that comes pretty close to what I am doing:

```nim
import std/[math, sequtils, strformat]
import ggplotnim

let
  fs = 100.0
  pxxDb = @[-191.5243109538998, -209.7186267027922, -232.2594043180185, -260.5427208848885,
            -297.3832809546469, -340.377384815329, -340.377384815329, float.low, float.low, -334.3567849020494,
            -333.3876847719688, -335.3258850321299, -346.3979847286086, -351.9555844453586,
            -353.3834456844492, -343.9815618770165, -350.4117593147899, -340.4695264529317,
            -354.4025139469563, -340.1113149084508]
  numPts = pxxDb.len
var
  upperLimit, lowerLimit: float
if numPts mod 2 == 0: # even e.g. 10 -> [-5, 5)
  upperLimit = numPts.float / 2
  lowerLimit = upperLimit
else: # odd e.g. 11 -> [-5, 6)
  upperLimit = (numPts.float+1) / 2
  lowerLimit = upperLimit-1

let
  # https://www.mathworks.com/help/matlab/ref/fftshift.html
  # https://github.com/numpy/numpy/blob/v1.17.0/numpy/fft/helper.py#L22-L76
  pxxDbFftShift = concat(pxxDb[upperLimit.int ..< numPts], pxxDb[0 ..< upperLimit.int])

let
  plotWidth = 720 # FIXME Make be later make this configurable via PlotConfig
  plotHeight = 480 # FIXME Make be later make this configurable via PlotConfig
  plotXLabel = "Frequency (Hz)"
  plotYLabel = "Power (dB)"
  plotFilePath = "fft.png"
var
  # Need the data as two sequences
  x: seq[float]
  y: seq[float]
for i in -lowerLimit.int ..< upperLimit.int:
  let
    xElem = (i.float * fs / numPts.float)
    yElem = pxxDbFftShift[i+lowerLimit.int]
  x.add(xElem)
  y.add(yElem)

# Create a dataframe from the data.
let df = seqsToDf({plotXLabel: x, plotYLabel: y })

echo &"Saving plot to {plotFilePath} .."
ggplot(df, aes(plotXLabel, plotYLabel)) +
  theme_opaque() + # https://github.com/Vindaar/ggplotnim/pull/41/files#diff-0c88c9acc6458974b569d4f97da31c85R539
  geom_line() +
  ggtitle("FFT") +
  ggsave(plotFilePath, width = plotWidth.float, height = plotHeight.float)
```

**Comment by Vindaar** [comment]
Thanks for the example! 

Regarding the `inf` values and your `tan` example. I'm not quite following. I mean I understand what your proposing; something like an overflow. But
1. the `tan` plot you include looks just like every other `tan` plot I've seen. That is it cuts off at `yMin`, `yMax` and leaves a space \Delta x from somewhere \pi - (\Delta x) / 2 to  \pi + (\Delta x) / 2 (etc.) where no points are present.
2. yes, it falsifies the plot. But so does an overflow. How do I know looking at the plot that a point in that overflow region is just smaller / larger than my `yMin` / `yMax` or whether it's `inf`?

**Comment by kaushalmodi** [comment]
> How do I know looking at the plot that a point in that overflow region is just smaller / larger than my yMin / yMax or whether it's inf

My assumption is that you are keeping some sort of buffer above the `yMin` and below the `yMax`.

So the only cases where the plot touch the absolute top/bottom of the plot would be for +inf/-inf.

Here's my poor annotation skills applied to one of your ggplotnim created plots :)

![image](https://user-images.githubusercontent.com/3578197/74991584-49a74700-5414-11ea-81f2-43b1c64ff394.png)

**Comment by Vindaar** [comment]
Ah, yes. That bit I understood. What I meant was something slightly different.

Namely, given some data, which has values in range `[yMin, yMax]`. Now we wish to restrict our plotting range to some `[yMinPlot, yMaxPlot]`. However, we may still have several `inf` values in the data too. With your buffer then, how do I differentiate between a point `y` that is e.g. :

- `yMaxPlot < y < yMax`
- and `y = inf`?

Since by definition both are outside of `[yMinPlot, yMaxPlot]` both belong into the overflow area.

To be fair, this currently doesn't make any sense, since there's *still* no way to manually change the shown ranges, but obviously that's not gonna stay that way. 

One can arguably put `inf` values to the very end of the buffer and those other normal, but larger than `yMaxPlot` values in between. But then the position where they belong isn't well defined, since the range of the overflow is always infinite.

From an implementation standpoint such an overflow would easiest be implemented by extending the scale by `N %` and capping all `inf` values to that `yMaxPlot * (1 + N)` range. 

I would propose to handle both of the above `y` cases the same way. They are overflown and we put them into the buffer zone. The user is responsible for choosing the visible range in such a way to not misrepresent any data.

**Comment by kaushalmodi** [comment]
> how do I differentiate between a point y that is e.g. :
> - yMaxPlot < y < yMax
> - and y = inf?

we will always have `y < yMax` because y is the max y except for when y is +/- inf. I am giving +/-inf a special status. So the plotting touching the yMaxPlot and yMinPlot happens only when y is `float.max` (+inf) or `float.min` (-inf).

That said, I don't have any opinion on how to implement this.

> The user is responsible for choosing the visible range in such a way to not misrepresent any data.

I am open to your proposal.

**Comment by Vindaar** [comment]
> > how do I differentiate between a point y that is e.g. :
> > 
> > * yMaxPlot < y < yMax
> > * and y = inf?
> 
> we will always have `y < yMax` because y is the max y except for when y is +/- inf. I am giving +/-inf a special status. So the plotting touching the yMaxPlot and yMinPlot happens only when y is `float.max` (+inf) or `float.min` (-inf).

But what I mean is that your horizontal red line in your plot above corresponds to `yMaxPlot`. The buffer is zone is beyond that. The place where `+-inf` goes is at relative `0` and `1`, whereas `yMin/MaxPlot` end somewhere before.

Sorry for being confusing. I think I'm not making the most sense anymore. I'm tired and need some sleep, haha.

**Comment by kaushalmodi** [comment]
> But what I mean is that your horizontal red line in your plot above corresponds to yMaxPlot. The buffer is zone is beyond that. 

OK, that makes sense :)

> Sorry for being confusing. I think I'm not making the most sense anymore. I'm tired and need some sleep, haha.

My apologies as well.. I think we are both approaching this problem from different perspectives. I will wait and see your proposal and understand it better. As long as there's a way to specially handle the +/-inf, even from the user-side, it will work out for me.

_btw, I pinged you on https://gitter.im/Vindaar as I was not sure where to have quick Q&A regarding annotations. I can open a new issue for that if you prefer._

**Comment by Vindaar** [comment]
With #46 merged this should now be easily possible.

Note that we perform clipping of values outside the range by default now. So if all you wanted was clipping of `inf` without a buffer zone, that is what we do now. To get a buffer zone, just add a margin via `x/yMargin`. 

Let me know if it works for you and feel free to reopen!

**Comment by kaushalmodi** [comment]
Thanks! The fix works perfectly without changing any ggplotnim configuration on my side. It now handles the +/-inf values.

**Comment by kaushalmodi** [comment]
![image](https://user-images.githubusercontent.com/3578197/75368003-1f7bdc00-588f-11ea-9eaf-f4f3392b0f2d.png)
